# This is a YAML file
#
# The following structure is used:
# 
# output_dir:
#   - service endpoint 1
#   - service endpont 2
# different_output_dir:
#   - service endpoint 3
#
# The SOS title will be used for the output filename, but this can
# be overridden by specifying: 
#
#   - service endpoint 4 : "service-file-name"

ioos:
  - http://sdf.ndbc.noaa.gov/sos/server.php
  - http://opendap.co-ops.nos.noaa.gov/ioos-dif-sos/SOS
  - http://www.neracoos.org/cgi-bin/sos/V1.0/oostethys_sos.cgi
  - http://neptune.baruch.sc.edu/cgi-bin/ioos_sos.cgi 
  - http://sccoos-obs0.ucsd.edu/sos/server.php : "sccoos-sos"
